/*
 (c) Skimlinks 2009-2020
 Build time: Thu, 15 Oct 2020 13:10:13 GMT
 Version: "14.4.0-stackpath"
*/
(function(){function Ab(a){v(dd,function(b){null!==b.iabVendorId&&Bb(b.iabVendorId,a)});v(y.partner_consents,function(b,c){var d=wa();var e=D(y,["partner_consents",String(c)]);d=46!==c&&e?e.consent:d;d!==a&&Bb(c,a)});xa(y,["skimlinks_consent"],a)}function Bb(a,b){xa(y,["partner_consents",String(a),"consent"],b)}function wa(){return D(y,["skimlinks_consent"],null)}function ed(a){function b(a,b){if(!(!a.parentNode||ya(a,e)||a.meta&&a.meta.ReadOnly)){var c=fd(a,b)[0];v(c,function(a){!g[a]&&gd(a)&&(g[a]=
!0,p.domain_data.domains.push(a))})}}var c=z.get_as_hash_node_dict(),d=Object.keys(c).length;if(d){var e=hd(id.concat(Db())),g={},n=W(function(a){X(a)}),h=0;v(c,function(c,e){window.setTimeout(function(){try{b(c,e)}catch(Cb){n(Cb)}finally{h+=1,h===d&&a(Object.keys(g))}},0)})}else a([])}function jd(a){var b;var c=b=null;var d=5;a.Limit&&(d=a.Limit);var e=function(){return a.Priority||0};return{group_id:function(){return b?b.id():0},dec_limit:function(){return d-1},limit:function(){return d},action_type:function(){return a.ActionType},
text:function(){return a.OriginalPhrase},start_byte:function(){return a.StartByte},url:function(){return a.Url},multi:function(){return a.Mt?!0:!1},group_priority:function(){return b?b.group_priority():e()},id:function(){return c?c:a.PhraseId},groups:function(){var b;return(b=a.Groups)?b:[]},title:function(){return a.Unlinked?"":null!=a.ActionTitle?a.ActionTitle:"Shopping link provided by SkimWords"},set_title:function(b){a.Title=a.Unlinked?"":b},occurrence:function(){return a.PhraseOccurrence},set_group:function(a){return b=
a},set_id:function(a){return c=a}}}function kd(){var a=w.linksImpressions;a={phr:a.skimwords.urls,unl:a.unlinked.urls,slc:a.skimlinks.count,swc:a.skimwords.count,ulc:a.unlinked.count,jsl:(new Date).getTime()-w.loading_started,pref:k.referrer,uc:za,t:1,jsf:"",jv:ea};fa&&(a.xrf=1);return Eb(a)}function Fb(a,b){var c=a.style.cssText;""!==c&&(c+=" ");var d=f("link_background");d&&(-1===d.indexOf("#")&&(d="#"+d),c+="background-color: "+d+" !important; ");null!==f("link_tooltip",null)&&(a.title=f("link_tooltip"));
b&&(Sa&&(d=Sa,-1===d.indexOf("#")&&(d="#"+d),c+="color: "+d+" !important; "),Ta&&(c+="font-weight: "+Ta+" !important; "),ha&&(c="double"===ha?c+"border-bottom: 1px double !important; ":"dashed"===ha?c+"border-bottom: 1px dashed !important; ":c+("text-decoration: "+ha+" !important; ")),Ua&&(c+="font-style: "+Ua+" !important; "),f("skimwords_link_style")&&(d=f("skimwords_link_style"),c+=d+"; "),f("skimwords_link_class")&&(a.className=C(a.className+" "+f("skimwords_link_class"))),Va&&(a.title=Va),null===
a.getAttribute("title")&&(a.title="Shopping link added by SkimWords"),a.getAttribute("data-skim-creative")&&(d=parseInt(a.getAttribute("data-skim-creative"),10)%10,1===d||2===d))&&(a.title="");a.style.cssText=c;return!0}function Wa(a,b){b=b||Gb(a);if(!b)return!0;Hb(b);var c=f("skimlinks_keywee_pixel",null);var d=r(m.location.href,"utm_campaign=fbkw");c&&d&&Ib(c);f("vglnk")&&Y(b,"skimwords-link")&&(a&&a.stopPropagation?a.stopPropagation():(c=m.event,c.cancelBubble=!0));return!0}function Hb(a,b){a&&
a.nodeName&&"A"!==a.nodeName.toUpperCase()&&"AREA"!==a.nodeName.toUpperCase()&&(a=Jb(a));if(a){var c=ld(a);var d=p.waypointDomain;if(c.length>=d.length&&c.substr(0,d.length)===d)return!0;if(-1!==c.indexOf(d))d=c;else{d=a;var e=Y(d,"skimwords-link"),g=E(d,"data-skim-creative"),n=E(d,"data-skimlinks-tracking")||za,h=Xa?"&"+Xa:"";c=A(Ya(),{id:Kb,isjs:1,jv:ea,sref:m.location,url:c,xguid:k.cookie,xs:1,xtz:Lb(),xuuid:k.uuid});g&&(c.xcreo=g);k.isAdblockUser&&(c.abp=1);Z&&(c.site=Z);n&&(c.xcust=n);e&&(c.xs=
2,c.xword=E(d,"data-skimwords-word")||"");e=H(d);e.icust&&(c.xjsf=e.icust);e.sourceApp&&(c.xs=e.sourceApp);e.clientClickId&&(c.cci=e.clientClickId,delete H(d).clientClickId);e.linkSwappingMatchId&&(c.ls=e.linkSwappingMatchId);d=p.waypointDomain+"/?"+ia(c)+h}Mb(a,d,b)}return!0}function Jb(a){for(;a.parentNode;){a=a.parentNode;var b=a.nodeName.toUpperCase();if("A"===b||"AREA"===b)return a}return null}function Nb(a,b,c){a=D(m,["skimlinks_settings",a],m[a]);return L(a)?b:q(c)?c(a,b):a}function f(a,b,
c){if(T(a)){a:{void 0===a&&(a=[]);for(var d=0;d<a.length;d++){var e=Nb(a[d]);if(!L(e)){if(q(c)){b=c(e,b);break a}b=e;break a}}}return b}return Nb(a,b,c)}function Ob(){return D(Aa(),["runTimeInfo","isAdblockUser"])}function M(a){return a.replace(/^www\./i,"")}function Za(){for(var a="",b=0;8>b;b++)a+=Math.floor(65536*(1+Math.random())).toString(16).substring(1);return a}function q(a){return"[object Function]"===Object.prototype.toString.call(a)}function I(a,b,c){for(var d=0,e=null===a?0:a.length;d<
e;)c=b(c,a[d],d,a),d+=1;return c}function Ba(a){return"console"in window&&q(window.console[a])?window.console[a]:function(){}}function Ca(a,b){return I(b,function(b,d){return b&&q(a[d])},!0)}function md(){try{var a=JSON.stringify({a:1});return 1===JSON.parse(a).a}catch(b){return!1}}function B(a,b){var c=Error(b);c.name=a;Pb(c,"getPrototypeOf"in Object?Object.getPrototypeOf(this):this.__proto__);Error.captureStackTrace&&Error.captureStackTrace(c,B);return c}function Pb(a,b){"setPrototypeOf"in Object?
Object.setPrototypeOf(a,b):a.__proto__=b}function L(a){return"undefined"===typeof a||null===a}function T(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)}function G(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function v(a,b){if(T(a))for(var c=0;c<a.length;c++)b(a[c],c,a);else for(c in a)G(a,c)&&b(a[c],c,a)}function A(){var a=arguments[0],b=Array.prototype.slice.call(arguments,1);L(a)&&(a={});v(b,function(b){L(b)&&(b={});v(Object.keys(b),function(c){a[c]=
b[c]})});return a}function Da(a,b){var c=[];v(a,function(d,e){b(d,e,a)&&c.push(d)});return c}function Qb(a){void 0===a&&(a=[]);return Da(a,function(a){return!!a})}function $a(a,b){if(!a)return[];if(!b)return[].concat(a);var c=[];v(a,function(d,e){c.push(b(d,e,a))});return c}function C(a){return L(a)?"":a.toString().replace(/^[\s\xA0]+|[\s\xA0]+$/g,"")}function J(a){return"boolean"===typeof a}function U(a,b){return"undefined"===typeof a?b:a}function ab(a,b,c){a=U(a,"");b=U(b,"");c=U(c,0);return 0===
a.slice(c).indexOf(b)}function Ea(a,b,c){a=U(a,"");b=U(b,"");c=U(c,0);c=c<a.length?c|0:a.length;return a.substr(c-b.length,b.length)===b}function Rb(a){return encodeURIComponent(a).replace(/[!'()*~]/g,function(a){return"%"+a.charCodeAt(0).toString(16).toUpperCase()})}function ja(a,b){void 0===b&&(b=!0);var c=document.createElement("a");if(b)var d=a;else{d=void 0;void 0===d&&(d="http");var e="";/^https?:\/\//.test(a)||/^\/[^/]+/.test(a)||(e=/^\/\//.test(a)?d+":":d+"://");d=""+e+a}c.href=d;try{return M(c.hostname)}catch(g){return""}}
function Sb(a){a=a.replace(/^\??/,"").split("&");return I(a,function(a,c){if(!c)return a;var b=c.split(/=/),e=b[0];if(1===b.length)return a[e]=!0,a;a[e]=decodeURIComponent(b.splice(1).join(""));return a},{})}function Tb(a){var b=Sb(window.location.search);return G(b,a)}function ia(a,b){var c=[];b=b||Rb;v(a,function(a,e){c.push(e+"="+b(a))});return c.join("&")}function bb(a,b,c,d){function e(){if(q(d.onError)){var b=400<=t.status&&500>t.status,c=500<=t.status&&600>t.status;d.onError(new (0===t.status?
nd:b?od:c?pd:qd)(h+" "+a+" "+t.status))}}b=b||{};d=d||{};var g=d.data,n=d.headers||{},h=d.method||"GET",t=new XMLHttpRequest;d.withCredentials&&(t.withCredentials=!0);b=ia(b);b.length&&(a=a+"?"+b);t.open(h,a);v(n,function(a,b){t.setRequestHeader(b,a)});t.onload=function(){if(q(c))if(200<=t.status&&300>t.status){try{var a=JSON.parse(t.responseText)}catch(Cb){a=t.responseText}c(a)}else e()};t.onerror=e;t.send(g);return t}function D(a,b,c){if(!a||!b||!b.length)return c;for(var d=b.length,e=0;e<d;e++){var g=
b[e];if(a&&g in a)a=a[g];else return c}return a}function Aa(){return window.__SKIM_JS_GLOBAL__&&q(window.__SKIM_JS_GLOBAL__.getDebugInfo)?window.__SKIM_JS_GLOBAL__.getDebugInfo():{}}function rd(a){var b=/(?::(\d+))?:(\d+)$/,c=/^([^ ]+)\s\((.*)\)$/,d={filename:a,"function":"?",lineno:null,colno:null,in_app:!0};c.test(a)&&(a=a.match(c).slice(1),c=a[1],d["function"]=a[0],d.filename=c);b.test(d.filename)&&(c=d.filename.match(b).slice(1),a=c[0],c=c[1],a&&c?(d.lineno=parseInt(a,10),d.colno=parseInt(c,10)):
!a&&c&&(d.lineno=parseInt(c,10)),d.filename=d.filename.replace(b,""));return d}function sd(a){a=a.stack.replace(a.toString(),"").replace(/^\s+at\s+/gm,"").split("\n");a=$a(a,function(a){return C(a)});a=Qb(a);a.reverse();return $a(a,rd)}function X(a,b){if(a&&Ub){Vb.push(a);try{td.sendError(a,b)}catch(d){if(d===a)Wb.error(a);else{var c=new ud;c.__sentryExtraData__={logger_error_message:d.message,logger_error_stack:d.stack,initial_error_message:a.message,intial_error_stack:a.stack};throw c;}}}}function F(a){return q(a)?
function(){try{a.apply(this,arguments)}catch(b){X(b)}}:a}function W(a){var b=!1,c;return function(){if(b)return c;c=a.apply(this,arguments);b=!0;return c}}function Xb(a,b){return T(a)?a:b}function E(a,b,c){3<=arguments.length&&("undefined"!==typeof a.setAttribute?a.setAttribute(b,c):a[b]=c);try{var d=a[b];d||(d=a.getAttribute(b));return d}catch(e){return null}}function K(a,b){var c=Array.prototype.slice.call(arguments,2),d=F(a);return window.setTimeout.apply(window,[d,b].concat(c))}function vd(a,
b){function c(){a.href=a.skimlinksOriginalHref;delete a.skimlinksOriginalHostname;delete a.skimlinksOriginalHref;delete a.skimlinksRestoreSwappedLink}b=b||Yb;var d=K(c,b);a.skimlinksOriginalHostname=a.hostname;a.skimlinksOriginalHref=a.href;a.skimlinksRestoreSwappedLink=function(){clearTimeout(d);c()}}function Mb(a,b,c){if(a){"string"===typeof a.skimlinksOriginalHref||vd(a,c);c=null;var d=a.childNodes.length&&3===a.childNodes[0].nodeType;"msie"===k.detect.browser&&d&&(c=a.innerHTML);a.href=b;c&&c!==
a.innerHTML&&(a.innerHTML=c)}}function cb(a,b){var c=b?b.charAt(0).toUpperCase()+b.slice(1):"";return a["skimlinksOriginal"+c]||a[b]}function Zb(a){var b=a.href;b=k.cookie?b.replace(/([&?])xguid=([a-fA-F0-9]{32})/,"$1xguid="+k.cookie):b.replace(/([&?]xguid=[a-fA-F0-9]{32})/,"");b!==a.href&&Mb(a,b);return b}function $b(a){a=a||document;a=a.body||a.getElementsByTagName("body")[0];if(!a)throw new ac;return a}function Ib(a,b,c){if(!N){N=document.createElement("iframe");N.id="skimlinks-pixels-iframe";
try{$b().appendChild(N)}catch(g){g instanceof ac&&document.documentElement.appendChild(N)}var d=N;d.width=0;d.height=0;d.style.display="none"}var e=N.contentDocument||N.contentWindow.document;d=$b(e);d||(d=document.createElement("body"),e.appendChild(d));e=e.createElement("img");e.src=a;e.width=1;e.height=1;q(b)&&(e.onload=F(b));q(c)&&(e.onerror=F(c));d.appendChild(e)}function Ya(){var a={};db&&(a.dnt=db);bc&&(a.fdnt=1);return a}function ka(a,b,c,d){var e=d||{};d=e.usePixel||!1;var g=e.useSendBeacon||
!1;e=e.callback||function(){};c=A({},c,Ya());g?cc(a,b,c,e):d?dc(a,b,c,e):eb(a,b,c,e)}function cc(a,b,c,d){b=JSON.stringify(b);return navigator.sendBeacon&&(a=fb(a,c),navigator.sendBeacon(a,b))?(d&&d(),!0):!1}function dc(a,b,c,d){c=A({},c);c.rnd=Math.random();b&&(c.data=JSON.stringify(b));Ib(fb(a,c),d,d)}function eb(a,b,c,d){b=JSON.stringify(b);Fa.post(fb(a,c),{},d,{headers:{"Content-type":"text/plain"},data:b,withCredentials:!0})}function fb(a,b){var c=ia(b),d=""+wd+a;return c?d+"?"+c:d}function r(a,
b){return q(a.indexOf)?-1<a.indexOf(b):!1}function Ga(a){var b=M(Ha);return r(a,ec)||r(a,"go.redirectingat.com")||!!b&&r(a,b)}function l(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c;return a}function xd(a,b){if(!a)throw Error("[matchSelector] First argument needs to be an html element.");var c=window.Element.prototype;c=c.matches||c.msMatchesSelector||c.mozMatchesSelector||c.webkitMatchesSelector;if(q(c))try{return c.call(a,b)}catch(e){return!1}c=
(a.document||a.ownerDocument).querySelectorAll(b);for(var d=0;c[d]&&c[d]!==a;)d+=1;return!!c[d]}function ya(a,b){var c=yd(a);if(!c||!T(b)||0===b.length)return!1;var d=b.map(function(a){return a+" *"}).concat(b).join(",");return xd(c,d)}function yd(a){for(;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.parentNode;return a}function gb(a,b){for(var c=0;c<a.length;c++)if(b(a[c]))return a[c]}function aa(a,b){if("function"!=typeof a||null!=b&&"function"!=typeof b)throw new TypeError("Expected a function");if(!aa.Cache)return a;
var c=function e(){for(var c=arguments.length,n=Array(c),h=0;h<c;h++)n[h]=arguments[h];c=b?b.apply(this,n):n[0];h=e.cache;if(h.has(c))return h.get(c);n=a.apply(this,n);e.cache=h.set(c,n)||h;return n};c.cache=new aa.Cache;return c}function fc(a,b){return!!gb(b,function(b){var c=ab("*"),e=Ea("*"),g=b.replace(/\*/g,"");return c&&e?r(a,g):c?Ea(a,g):e?ab(a,g):a===b})}function hb(a,b){return a&&a.length&&b?"undefined"!==typeof gb(a,b):!1}function zd(a){return f("_merchantSettings")?hb(Ad,function(b){return r(a,
b)}):!1}function gc(a){if(!a||!a.href)return!0;var b=C(cb(a,"href"));(b=!hc(b))||(b=[].concat(Bd(),Db(),ic),b=b.length&&ya(a,b)?!0:ib.length?!ya(a,ib):!1);return b}function hc(a){if(!a||zd(a))return!1;var b=p.hostname;var c=U(void 0,!0);c=ja(a,c);var d=Ea(c,"."+b)||Ea(b,"."+c);if(b=c!==b&&!d)a=ja(a),a=Ia.length?!fc(a,Ia):fc(a,Cd()),b=!a;return b}function Dd(a){var b;if(b=jc)null===a.offsetParent?b=!0:(b=m.getComputedStyle,b=q(b)?"hidden"===b(a).visibility:!1);if(b)return x.IGNORE;var c=C(cb(a,"href"));
b=M(cb(a,"hostname"));c=c?/^https?:\/\//.test(c)||/^\/\//.test(c):!1;if(c&&!gc(a)){if(fa)return x.TRACK;if(!0===p.aff_domains[b]||G(jb,b))return x.AFFILIATE;if(Ga(b))return x.PRE_AFFILIATED;if(a=kb)a=!G(p.aff_domains,b)||L(p.aff_domains[b]);return a?x.UNKNOWN:""===k.cookie&&kc?x.AFFILIATE:x.TRACK}return x.IGNORE}function Y(a,b){if(!a||!a.className||!b)return!1;var c=a&&a.className?C(a.className).split(/\s+/):[];return r(c,b)}function xa(a,b,c){if(!a||!b||!b.length)return a;for(var d=b.length,e=a,
g=null,n=0;n<d;n++){var h=b[n];if(n===d-1){try{a[h]=c}catch(t){e[g]={},e[g][h]=c}break}(e=!(h in a))||(e=a[h],g=typeof e,e=!(null!==e&&("object"===g||"function"===g)));e&&(a[h]={});e=a;g=h;a=a[h]}return a}function Ja(a){if("string"!==typeof a.skimlinksOriginalHref)return!1;var b=H(a),c=a.href,d=document.createElement("a"),e={};d.href=c;if(c=d.search.substring(1))for(c=c.replace(/&amp;/g,"&").split("&"),d=0;d<c.length;d++){var g=c[d].split("="),n=g[1];e[g[0]]=n?decodeURIComponent(n):null}b.icust&&
b.icust!==e.xjsf&&(e.xjsf=b.icust);b.sourceApp&&b.sourceApp!==e.xs&&(e.xs=b.sourceApp);b=ia(e);a.href=p.waypointDomain+"?"+b;return!0}function H(a){if(!a)throw Error("getAnchorMetaData takes an anchor HTML element as an argument");var b=D(a,[lc]);b||(b={icust:null,sourceApp:null},xa(a,[lc],b));return b}function mc(a,b,c){b=A({},b,{domain_id:la,publisher_id:ma,page_url:m.location.href,impression_id:k.uuid,jv:ea});var d={};navigator.sendBeacon?d.useSendBeacon=!!c:d.usePixel=!!c;ka("/generic_tracking/"+
a,b,{},d)}function Gb(a){a=a.target||a.srcElement||a.originalTarget;if(!a)return null;var b=(a.nodeName||"").toLowerCase();return r(["a","area"],b)?a:Jb(a)}function Ka(a){try{return a()}catch(b){}}function Ed(a){var b=f("gtag");Ka(function(){b("event",ba,{event_category:"click",event_label:a})})}function Fd(a){var b=f("ga");Ka(function(){b("send","event","click",ba,a)})}function Gd(a){var b=f("_gaq");Ka(function(){b.push(["_trackEvent","click",ba,a])})}function Hd(a){var b=f("pageTracker");b._trackPageview&&
Ka(function(){b._trackPageview("/"+ba+"/"+a)})}function Id(a,b){return I(Object.keys(b),function(c,d){var e=a[d]===b[d];return c&&e},!0)}function nc(a){return I(a,function(a,c){return a.concat(c)},[])}function La(a,b){void 0===b&&(b=!0);var c=a?"."+a:"";return nc(O.querySelectorAll(b?"a[href]"+c+", area[href]"+c:"a[href]"+c))}function Jd(a,b){v(a,function(a){var c=r(b,a)&&!Ga(a);p.aff_domains[a]=c})}function Kd(a,b){return!hb(a,function(a){return!b(a)})}function Ld(){for(var a=new P,b=arguments.length,
c=Array(b),d=0;d<b;d++)c[d]=arguments[d];a.waitFor(c);return a}function na(a){var b=oc[a];if(!b)throw Error("Unknown service "+a);return b}function Md(a){var b=E(a,"rel"),c=M(a.hostname);!b&&c&&!0===p.aff_domains[c]&&E(a,"rel","nofollow")}function Nd(){pc&&v(La(),Md)}function Od(a){if(a.affiliationType===x.IGNORE)return!1;var b=a.anchor,c=a.affiliationType,d=a.nativeEvent;if(a.type===V.LEFT_CLICK)if(b=a.anchor,c=a.affiliationType,c===x.AFFILIATE||c===x.UNKNOWN){b=a.anchor;c=a.nativeEvent;d=a.clientClickId;
var e,g,n;if(n=f("skimlinks_strip_attribute",!1))for(g in n)if(G(n,g)){var h=n[g];(e=E(b,g))&&0===e.indexOf(h)&&(e=e.substr(h.length),E(b,g,e))}oa&&E(b,"target",oa);H(a.anchor);H(b).clientClickId=d;Ja(b);ba&&(a=b.href,f("gtag")?Ed(a):f("ga")?Fd(a):f("_gaq")?Gd(a):f("pageTracker")&&Hd(a));a=qc?(a=E(b,"onclick"))&&r(a.toString(),"return false")?!0:(a=b.onclick)&&q(a)&&r(a.toString(),".preventDefault()")?!0:!1:!1;a?(Wa(c,b),(oa?m.open(b.href,oa):m.open(b.href,"_blank")).focus()):Wa(c,b)}else c===x.PRE_AFFILIATED?
Zb(b):c===x.TRACK&&(a={publisher_id:ma,publisher_domain_id:la,referrer:m.location.toString(),pref:k.referrer,site:""+Z,url:b.href,custom:E(b,"data-skimlinks-tracking")||za||"",xtz:k.timezone,uuid:k.uuid,product:"1"},fa&&(a.xrf=1),ka("/naclicks",a,null,{usePixel:!0}));else{try{if(n=H(b),!n.icust||-1!==n.icust.indexOf("other_click__")){e="other_click__"+d.type+" ["+(void 0!=d.button?d.button:"")+"]";if(32<String(e).length)throw Error(e+" is not a valid icust value. The value should be less than 33 chars");
H(b).icust=e;Ja(b)}}catch(t){}c===x.AFFILIATE||c===x.UNKNOWN?Hb(b,200):c===x.PRE_AFFILIATED&&Zb(b)}return!0}function Pd(){na(Q.ANCHOR_CLICK_INTERCEPTOR).registerInterceptor(Od,pa.SKIMLINKS)}function Qd(){k.skimlinksEnabled&&(u.on("skim_js_start",Pd),R.whenBeaconFullyReady(Nd))}function rc(a){var b;return a&&-1!==a.indexOf("class=")&&(b=a.match(/([^[]+)\[class=([^\]]+)\]/i))&&3===b.length?b[1]+"."+b[2]:a}function Rd(){var a=La();return I(a,function(a,c){var b,e=(b=M(c.hostname))&&!gc(c)&&!Ga(b),g=
G(p.aff_domains,b);e&&!g&&(a.push(b),p.aff_domains[b]=null,p.domain_data.domains.push(b));return a},[])}function sc(a){var b=Rd();return R.sendBeaconRequest(b,a)}function tc(a,b){v(a,function(a){void 0===p.aff_domains[a]&&(p.aff_domains[a]=null)});R.sendBeaconRequest(a,ca.AUX).readyState.whenReady(b)}function Eb(a){return A({pag:m.location.href,guid:k.cookie,uuid:k.uuid,tz:k.timezone,publisher_id:ma,publisher_domain_id:la},a)}function uc(a){if(0!==w.awaitedModules.length&&(w.awaitedModules=Da(w.awaitedModules,
function(b){return b!==a}),0===w.awaitedModules.length)){var b=kd();ka("/page",b)}}function Sd(a){a=a.match.phrase;return{w:a.text(),lp:a.url(),t:Ma.creative}}function Td(a){a=a||[];var b=I(a,function(a,b,e){a[e]=b;return a},{});w.linksImpressions.unlinked={count:a.length,urls:b};uc("unlinked")}function lb(a){return String(a).replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function hd(a){return I(a,function(a,c){return r(a,c)?a:a.concat(c)},[])}function mb(a,
b,c,d){void 0===d&&(d=!1);if(a&&(a.nodeName||a===m))if(O.addEventListener){var e=F(c.bind(a));a.addEventListener(b,e,d)}else a.attachEvent("on"+b,function(){return 7>k.detect.version&&!m.event?(K(c.bind(a,m.event),100),!0):c.call(a,m.event)})}function vc(a,b){Wa(a,b)}function Ud(){m.__SKIM_JS_GLOBAL__.bundledEntries.unlinked=!0;if(k.unlinkedEnabled){if(k.skimwordsEnabled)u.on("instant_api_callback_settings",Vd);else R.whenPostPageLoadBeaconCallCompleted(wc);u.on("dom_changed",xc)}}function nb(a){Wd.setReady();
Td(a)}function Vd(){var a=qa.settings;2===a.nc?k.unlinkedEnabled&&tc(p.domain_data.domains,yc):k.unlinkedEnabled&&(a.includes?(S&&S.length&&(a.excludes=a.excludes.concat(S)),z.traverse(a.includes,a.excludes,a.read_onlys)):S&&S.length?z.traverse(["body"],S,[]):z.traverse(["body"],[],[]));wc()}function wc(){a:{var a=O.getElementsByTagName("body");if(a.length){a=a[0].textContent||a[0].innerText;var b;if(b=a)a=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^[\]\s]*\b|$/gi.exec(a),
b=a.length&&""!==a[0]?!0:!1;if(b){a=!0;break a}}a=!1}a?(k.skimwordsEnabled||z.traverse([],S,[]),xc()):nb()}function xc(){ed(function(a){a.length?tc(a,yc):nb()})}function yc(){var a=[];Object.keys(p.aff_domains).length&&(v(Ma.url_spans,function(b){p.aff_domains[b.match.domain]&&(Xd(b.node,b.match,!0),a.push(Sd(b)))}),K(function(){var a;var c=La("skimlinks-unlinked");var d=[];var e=0;for(a=c.length;e<a;e++){var g=c[e];d.push(Yd(g))}return d},10));nb(a)}function Zd(a){var b=Math.random(),c=0;return gb(a,
function(a){a=c+a.weight;if(b<a)return!0;c=a;return!1})}function $d(a){a=a.reduce(function(a,c){var b=parseFloat(c.weight);(isNaN(b)||0>b||1<b)&&zc('"weight" field should be a number between (0, 1].');return a+b},0);1!==a&&zc("Sum of all the weights should be equal 1 but got "+a+".")}function ae(a){return hb(a,function(a){return G(a,"weight")})}function zc(a){throw Error("Error in variants setup. "+a);}function ob(a,b,c,d,e){d=((d||0)/1E3).toFixed(2);b={consent:a,publisher_domain_id:la,publisher_id:ma,
decision_time:parseFloat(d),test_case:Na.id,page_url:b,destination_url:c};Ac.setItem("skimCONSENT",a);ka("/consent",b,null,{callback:e})}function be(a){var b={nocache:Date.now()};Fa.get(Bc+"/iab",b,function(b){y=b;q(a)&&a(y)},{withCredentials:!0})}function pb(a){var b={};if(y){var c=wa();J(c)&&(b["46"]=c);v(y.partner_consents,function(a,c){J(a.consent)&&(b[c]=a.consent)})}c={nocache:Date.now()};Fa.post(Bc+"/iab",c,function(b){y=b;q(a)&&a(y)},{data:JSON.stringify(b),withCredentials:!0})}function ce(){var a=
k.country;a&&r(de,a.toUpperCase())?be(ee):(Cc.setReady(),u.publish("EVENTS__CONSENT_RESOLVED"))}function ee(){var a=k.consent,b=k.pageLocation,c=wa();J(a)&&null===c?(Ab(a),pb()):J(c)&&c!==a&&ob(c,b,"IAB_CONSENT_SYNC",0);Cc.setReady();u.publish("EVENTS__CONSENT_RESOLVED")}function fe(a,b){var c=A({},ge,b||{}),d=document.createElement("script");d.src=a;d.type="text/javascript";d.async=c.async;d.onload=F(c.onLoad);d.onerror=F(function(){X(new he(a));c.onError()});document.head.appendChild(d);return d}
function Dc(){if(window._isCypress)return!1;try{return window.top.document,!0}catch(a){return!1}}function qb(a){return Ec()[a]}function ie(a,b,c){Fc(a)&&Gc[a]===b?c(qb(a)):fe(b,{onLoad:function(){Fc(a)&&(Gc[a]=b,c(qb(a)))}})}function Fc(a){var b=Ec();return G(b,a)}function Ec(){ra.__SKIM_JS_GLOBAL__||(ra.__SKIM_JS_GLOBAL__={});ra.__SKIM_JS_GLOBAL__.modules||(ra.__SKIM_JS_GLOBAL__.modules={});return ra.__SKIM_JS_GLOBAL__.modules}function je(a,b,c){var d=document.createElement(a);v(b||{},function(a,
b){var c=b.split(".");xa(d,c,a)});"STYLE"===d.tagName&&(d.type="text/css");"SCRIPT"===d.tagName&&(d.type="text/javascript");Hc(d,[].concat(c||[]));return d}function Hc(a,b){v(b,function(b){if(T(b))Hc(a,b);else{var c="string"===typeof b;"STYLE"===a.tagName&&c&&a.styleSheet?a.styleSheet.cssText+=b:(c&&(b=document.createTextNode(b)),a.appendChild(b))}})}function ke(a){var b=C(a.skimlinksOriginalHref||a.href);return je("a",{href:b,target:"_blank"===a.target?"_blank":"_parent",rel:a.rel})}function Ic(a){var b=
qb(Na.moduleName);if(b){var c=ke(a);c.onclick=function(a){na(Q.ANCHOR_CLICK_INTERCEPTOR).triggerLeftClickFromMouseEvent(a,pa.SKIMLINKS)};var d=C(a.skimlinksOriginalHref||a.href),e="_blank"===a.target,g=k.pageLocation,n=Date.now(),h=W(function(a){var b=Date.now()-n;Ab(a);if(e)ob(a,g,d,b),pb(),c.click();else{var h=W(function(){c.click()}),t=0,f=function(){t+=1;2===t&&h()};ob(a,g,d,b,f);pb(f);K(h,1E3)}});new b({anchorClone:c,publisherDomain:M(p.hostname),merchantDomain:ja(d),onResolve:function(){return h(!0)},
onReject:function(){return h(!1)}})}}function le(){if(me()){var a=Na.moduleName,b=Na.getUrl;var c=Tb("skimlinks_locale");var d=Sb(window.location.search).skimlinks_locale;c=c?d:(c=D(y,["country"],k.country))?ne[c.toUpperCase()]||"en":"en";c=D(y,["locale"],c);b=b(c);ie(a,b,oe)}}function oe(){na(Q.ANCHOR_CLICK_INTERCEPTOR).registerInterceptor(pe,pa.CONSENT)}function pe(a){if(a.type!==V.LEFT_CLICK)return!1;var b=a.anchor,c=a.nativeEvent;a=a.affiliationType;a=a===x.AFFILIATE||a===x.PRE_AFFILIATED;if(!a)return!1;
c.preventDefault();Ic(b);return!0}function qe(){u.on("skim_js_init",function(){m.__SKIM_JS_GLOBAL__.bundledEntries.GDPRConsent=!0;m.skimlinksAPI.consent={openConsentModal:Ic}});u.on("EVENTS__CONSENT_RESOLVED",le)}function re(){return I(La(),function(a,b){var c=C(b.href),d=M(b.hostname),e;(e=!d)||(e=!(!Y(b,"skimwords-link")&&!Y(b,"skimlinks-unlinked")));(e=e||!hc(c))||(e=b&&T(Oa)&&0!==Oa.length?ya(b,Oa):!1);if(e)return a;(e=a.urls[c])||(e={count:0,ae:!0===p.aff_domains[d]||(null===p.aff_domains[d]||
void 0===p.aff_domains[d])&&kb&&!Ga(d)?1:0});e.count++;a:{if(-1!==c.indexOf("#slm-")&&(d=c.split("#slm-"),2===d.length&&!isNaN(d[1])&&10*parseInt(d[1],10)===10*d[1])){d=parseInt(d[1],10);break a}d=null}d&&(e.slmcid=d);d=e;1===d.ae&&a.count++;d.slmcid&&(e=d.slmcid,r(w.campaign_ids,e)||w.campaign_ids.push(e));if(!Jc&&0===d.ae)return a;a.urls[c]=d;return a},{urls:{},count:0})}function se(){v(te,function(a){var b=m;"skimlinks_context_window"===a&&(b=window);G(b,a)&&(a={page_var:a,value:JSON.stringify(b[a])},
mc("page_variable_tracking",a))})}function ue(){var a=W(function(){w.linksImpressions.skimlinks=re();uc("main-tracking");if(Object.keys(w.linksImpressions.skimlinks.urls).length){var a=Eb({dl:w.linksImpressions.skimlinks.urls,hae:w.linksImpressions.skimlinks.count?1:0,typ:"l"});ka("/link",a)}});R.whenNoRequestsPending(a);K(a,2E3)}function ve(){w.awaitedModules.push("main-tracking");k.skimwordsEnabled&&w.awaitedModules.push("skimwords");k.unlinkedEnabled&&w.awaitedModules.push("unlinked");Kc&&R.whenPostPageLoadBeaconCallCompleted(ue);
if(navigator.sendBeacon&&1>1E4*Math.random()){var a={domain_id:la,publisher_id:ma,page_url:m.location.href,impression_id:k.uuid,jv:ea},b=cc("/generic_tracking/trackingMethodExperiment",A({trackingMethod:"sendBeacon"},a));eb("/generic_tracking/trackingMethodExperiment",A({trackingMethod:"xhr"},a));b||eb("/generic_tracking/trackingMethodExperiment",A({trackingMethod:"sendBeaconFailed"},a))}}function we(){se()}function Lc(a,b){da||1E3<b?q(a)&&(da?rb?a(!0):a(!1):a(!1)):K(Lc,b*=2,a,b)}function Mc(){da||
(sa.complete&&ta.complete&&(da=!0),da&&"0"!=sa.width&&"0"==ta.width&&(rb=!0))}function xe(a){function b(a){return a.toLowerCase().replace(/^\/\/|^https?:\/\//,"")}var c=$a(Nc,b);return r(c,b(a))}function ye(){return{skimOptions:ze,runTimeInfo:A({},{aff_domains:p.aff_domains},{consentState:y},{loggedErrors:Vb},k)}}function Ae(a,b){var c=!1,d;return function(){if(c)return d;K(function(){c=!1},b);c=!0;return d=a.apply(this,arguments)}}function Oc(a,b,c,d){void 0===b&&(b=[]);if(a){var e=Ae(c,200);v(b,
function(b){try{mb(a,b,e,d)}catch(n){}})}}function Be(){var a=new Ce;oc[Q.ANCHOR_CLICK_INTERCEPTOR]=a}function De(){m.__SKIM_JS_GLOBAL__||(m.__SKIM_JS_GLOBAL__={});if(!m.__SKIM_JS_GLOBAL__.init){m.skimlinksAPI={};m.__SKIM_JS_GLOBAL__.init=!0;m.__SKIM_JS_GLOBAL__.getDebugInfo=ye;m.__SKIM_JS_GLOBAL__.bundledEntries=Ee;if(xe(p.hostname)||sb&&O.querySelector(sb))k.skimlinksEnabled=!1,k.skimwordsEnabled=!1,k.unlinkedEnabled=!1;"msie"===k.detect.browser&&8>=k.detect.version&&(k.skimwordsEnabled=!1);try{dc("/robots.txt",
void 0,{__skimjs_preflight__please_ignore__:!0})}catch(a){X(new Fe,!0)}Ge.detect(function(a){k.isAdblockUser=a});u.publish("skim_js_init");r(["interactive","complete"],O.readyState)?K(ua,0):(sc(ca.PRE_PAGE_LOAD),document.addEventListener("DOMContentLoaded",ua),document.addEventListener("load",ua));Be();u.publish("skim_js_start")}}var Wb={log:Ba("log"),info:Ba("info"),warn:Ba("warn"),error:Ba("error")},Ub=function(){var a=!0;try{var b=[md(),!!(window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest),
Ca(document,["querySelector","querySelectorAll"]),Ca(Object,["keys"]),Ca([],["indexOf"]),Ca("",["indexOf"])];a=I(b,function(a,b){return a&&b},!0)}catch(c){a=!1}!1===a&&Wb.info("[Skimlinks] Your browser doesn't support the base features necessary to run our javascript.");return a}();B.prototype=Object.create(Error.prototype,{constructor:{value:Error,enumerable:!1,writable:!0,configurable:!0}});Pb(B,Error);var ac=B.bind(null,"DocumentBodyNotFound"),He=B.bind(null,"PixelDropFailed"),he=B.bind(null,"ScriptDropFailed"),
qd=B.bind(null,"XhrError"),od=B.bind(null,"XhrError4xx"),pd=B.bind(null,"XhrError5xx"),nd=B.bind(null,"XhrErrorZero"),ud=B.bind(null,"SentryLoggerError");B.bind(null,"SendBeaconFailedError");var Fe=B.bind(null,"ResolveSslCertificateError");B.bind(null,"DisclosureReadyStateTimeout");var ea="14.4.0-stackpath",Ie="https://s.skimresources.com/js/GDPR",Je="https://r.skimresources.com/api/",jb={"t.umblr.com":{name:"z"}},Kb="725X1342",ma=725,la=1342,
wd="https://t.skimresources.com/api/v2",Bc="https://api.skimlinks.mgr.consensu.org",ec="go.skimresources.com",Ke="https://sl-sentry.skimlinks.com",Pc="f648b8dfc7284fad8af093653eafd6ca",Le="production",Me=1>1E3*Math.random(),td={sendError:function(a,b){if(!Pc)throw a;var c=b;c=(c=J(c)?c:!1)||Me?a instanceof He&&Ob()?!1:!0:!1;if(c){c=Ke+"/api/46/store/";var d={sentry_version:"7",sentry_client:"raven-js/3.26.4",sentry_key:Pc};var e={country:D(Aa(),["runTimeInfo","country"]),beacon_consent:D(Aa(),["runTimeInfo",
"consent"]),iab_consent:D(Aa(),["runTimeInfo","consentState","skimlinks_consent"]),is_adblock_user:Ob(),is_top_frame:window.top===window};e={event_id:Za(),project:"46",platform:"javascript",logger:"javascript",release:ea,exception:{values:[{type:a.name,value:a.message,stacktrace:{frames:sd(a)}}]},request:{headers:{"User-Agent":navigator.userAgent},url:location.href},extra:A({original_stacktrace:a.stack},a.__sentryExtraData__,e)};bb(c,d,null,{method:"POST",data:JSON.stringify(e)})}}},Vb=[],Lb=W(function(){return(new Date).getTimezoneOffset()}),
Qc=window.skimlinks_context_window||null,m=Qc?window[Qc]:window,O=m.document,Ac={getItem:function(a){try{return JSON.parse(localStorage.getItem(a))}catch(b){return null}},setItem:function(a,b){try{localStorage.setItem(a,JSON.stringify(b))}catch(c){}}},tb=f("noskim",!1),Ne=f("noskimlinks",!1),Oe=f("noskimwords",!0),Pe=f("nounlinked",!1),Qe=f("skimwords_standard",false),Re=f("skimwords_lite",false),Se=f("skimwords_diy",
false),Te=f("skimwords_diy_filter",false),Rc=!tb&&!Ne,Sc=!tb&&!Oe,Tc=!tb&&!Pe,db=f("skimlinks_dnt",0,function(a){return a&&"0"!==a&&"false"!==a?1:0}),bc=f("skimlinks_nocookie",!1),ub=f("skimlinks_excluded_classes",[]),ic=f("custom_excluded_selectors",[],Xb),ib=f("custom_included_selectors",[],Xb),vb=f("skimlinks_exclude",
[]),Ia=f("skimlinks_include",[]),jc=f("skimlinks_ignore_hidden_links",false),Oa=f("skimlinks_link_impression_exclude_selector",[]),pc=f("skimlinks_add_nofollow",false),Uc=f("skimlinks_before_click_handler",false,function(a,b){return J(a)?a:b}),kc=f("skimlinks_first_party_na",
!1),Ue=f("skimlinks_cookie_sync_optout",!0),Kc=!f("noimpressions",!1),Jc=false,Yb=f("skimlinks_replace_timeout",300,function(a,b){var c=parseFloat(a);return isNaN(c)?b:c}),kb=f("skimlinks_affiliate_unknown_links",true),oa=f("skimlinks_target",null),Ve=f("skimlinks_ajax_rerun",false),S=[],fa=f("skimlinks_revenue_forecast",
false),Vc=f("skimlinks_noright",false),Wc=f("skimlinks_url_extraction_rules",!1)||false,Xa=f("skimlinks_extra_redir_params",[]).join("&"),za=f(["affiliate_tracking","skimlinks_tracking"],!1),Pa=f("force_location"),Z=f(["skimlinks_site","skimlinks_sitename"],!1),Ha=f("skimlinks_domain","wordpress.redirectingat.com"),ba=f("skimlinks_google",false,function(a,b){return a?
J(a)?a?"skimout":"":C(a):b?"skimout":""}),Nc=f("noskim_domains",[]),We=f("skimwords_horizontal_distance",80),Xe=f("skimwords_vertical_distance",80),Ye=false,Sa=f("skimwords_color",null),Ta=f("skimwords_weight",null),ha=f("skimwords_decoration",null),Ua=f("skimwords_style",null),
Va=f("skimwords_title",null),sb=f("no_skim_selector",""),Xc=f("skimlinks_force_consent",!1),qc=true,ze={SW_STANDARD:Qe,SW_LITE:Re,SW_DIY:Se,SW_DIY_FILTER:Te,HAS_SKIMLINKS:Rc,HAS_SKIMWORDS:Sc,HAS_UNLINKED:Tc,DO_NOT_TRACK:db,NO_COOKIE:bc,SL_EXCLUDED_CLASSES:ub,CUSTOM_EXCLUDED_SELECTORS:ic,CUSTOM_INCLUDED_SELECTORS:ib,SL_EXCLUDED_DOMAINS:vb,SL_INCLUDED_DOMAINS:Ia,SL_IGNORE_HIDDEN_LINKS:jc,SL_IMPRESSION_EXCLUDED_SELECTORS:Oa,
SL_ADD_NOFOLLOW:pc,SL_BEFORE_CLICK_HANDLER:Uc,SL_FIRST_PARTY_NA:kc,SL_COOKIE_SYNC_OPTOUT:Ue,SL_TRACK_IMPRESSION:Kc,WITH_NA_LINK_IMPRESSIONS:Jc,SL_REPLACE_TIMEOUT:Yb,SL_AFFILIATE_UNKNOWN_LINKS:kb,SL_TARGET:oa,AJAX_SUPPORT:Ve,UNLINKED_EXCLUDES:S,SL_FORECAST:fa,NO_RIGHT_CLICK:Vc,USE_MERCHANT_URL_EXTRACTION_RULES:Wc,EXTRA_REDIR_PARAMS:Xa,CUSTOM_TRACKING_VAR:za,FORCE_LOCATION:Pa,SITE_NAME:Z,CUSTOM_WAYPOINT_DOMAIN:Ha,GOOGLE_TRACKING_ACTION_NAME:ba,NO_SKIM_DOMAINS:Nc,SW_HORIZONTAL_DISTANCE:We,SW_VERTICAL_DISTANCE:Xe,
SL_PROFILING:!1,TRACK_COOKIE_SYNCS:Ye,SW_LINK_COLOR:Sa,SW_LINK_WEIGHT:Ta,SW_LINK_DECORATION:ha,SW_LINK_STYLE:Ua,SW_LINK_TITLE:Va,NO_SKIM_SELECTOR:sb,SL_CONSENT:"ae",FORCE_CONSENT:Xc,M101_TRACKING_ID:null,M101_CUSTOM_DOM_DETECTION:false,AE_CLICK_TRACKING:!1,INCENTIVE_ENABLED:!1,FORCE_PREVENTED_CLICKS_MONETIZATION:qc,IS_MINIMALISTIC_JS:!1,LINK_SWAPPING_404:!1,LINK_SWAPPING_OUT_OF_STOCK:!1,LINK_SWAPPING_PRODUCT_MATCH:!1,LINK_SWAPPING:!1,
LINK_SWAPPING_MERCHANT_NAME_DETECTION:true},k=function(){var a=O.referrer||document.referrer||"",b=Pa||m.location.href;var c="aspsession-id aspsessionid cftoken j-sessionid jsessid jsession_id jsessionid phpsessid phpsession-id phpsessionid seskey sessid session-id session-key session_id sessionid sessionkey uniqueid utm_campaign utm_medium utm_source utm_term".split(" ");for(var d=0;d<c.length;d++){var e=c[d];var g=b.split("?");if(2<=g.length){b=
g.shift();g=g.join("?");e=encodeURIComponent(e)+"=";g=g.split(/[&;]/gi);for(var n=g.length-1;0<=n;n--)ab(g[n],e)&&g.splice(n,1);b=b+"?"+g.join("&")}}"?"===b[b.length-1]&&(b=b.substr(0,b.length-1));c=b;d=Ac.getItem("skimCONSENT");b=navigator.userAgent.toLowerCase();b=/(webkit)[ /]([\w.]+)/.exec(b)||/(opera)(?:.*version)?[ /]([\w.]+)/.exec(b)||/(msie) ([\w.]+)/.exec(b)||0>b.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(b)||[];b={browser:b[1]||"",version:parseFloat(b[2])||0};return{cookieSyncString:"",
lastBeaconTimestamp:null,cookie:"",country:"",locale:"",consent:d,detect:b,isAdblockUser:!1,pageLocation:c,referrer:a,timezone:Lb(),uuid:Za(),skimwordsEnabled:Sc,skimlinksEnabled:Rc,unlinkedEnabled:Tc}}(),p=function(){var a=document.getElementsByTagName("html")?document.getElementsByTagName("html")[0]:null,b=Pa?ja(Pa,!1):m.location.hostname;return{aff_domains:{},beacon:[],domain_data:{domains:[]},exclude:vb,exclude_lookup:null,excluded_classes:["noskimlinks","noskim"].concat(ub),has_been_called:!1,
hostname:b,html_root:a,include:Ia,include_lookup:null,links:[],links_tracked:!1,target:null,waypointDomain:Ha?"http://"+Ha:"https://"+ec}}();var qa={};var Ma={creative:"500005",url_spans:[]};var Yc=function(a,b,c){if(0===b)return c;try{return a()}catch(d){return Yc(a,b-1,c)}};get_real_link=function(a){if(null==a)return null;for(;"A"!==a.nodeName.toUpperCase();)if(a=Yc(function(){return a.parentNode},3,null),null==a)return null;return a};var N,Fa={get:function(a,b,c,d){d=A({onError:X},d,{method:"GET"});
bb(a,b,F(c),d)},post:function(a,b,c,d){d=A({onError:X},d,{method:"POST"});bb(a,b,F(c),d)}};"undefined"!==typeof window.Map&&(aa.Cache=Map);var Ze=["noskim","norewrite"],$e=["noskimlinks","noskim"].concat(["taboola","advert--taboola","trc_rbox","trc_related_container"]),af="*.criteo.com *.g.doubleclick.net *mjxads.internet.com *overture.com *pgpartner.co.uk *pgpartner.com *pricegrabber.co.uk *pricegrabber.com *youtube.com m.skimresources.com paid.outbrain.com track.celtra.com traffic.outbrain.com trc.taboola.com zergnet.com ad.doubleclick.net".split(" "),
Ad=["itunes.apple.com","itunes.com","phobos.apple.com"],Cd=aa(function(){var a=[].concat(vb,af);Z&&a.push(Z);return a}),Db=aa(function(){return $e.concat(ub).map(function(a){return"."+a})}),Bd=aa(function(){return Ze.map(function(a){return"a[rel~='"+a+"']"})}),bf=function(){var a=/[-[\]{}()*+?.,\\^$|#]/g,b=/\s+/g;return function(c){return c.replace(a,"\\$&").replace(b,"\\s+")}}(),x;(function(a){a.AFFILIATE="AFFILIATE";a.PRE_AFFILIATED="PRE_AFFILIATED";a.UNKNOWN="UNKNOWN";a.TRACK="TRACK";a.IGNORE=
"IGNORE"})(x||(x={}));var lc="__skimlinks__";var ld=function(a){var b;if(Wc){var c=M(a.hostname);if(c in jb)return c="[&?]"+jb[c].name+"=(http[^&]+)",c=new RegExp(c),decodeURIComponent(null!=(b=a.href)?b.match(c).pop():void 0)||a.href}return a.href};var Zc;(function(a){a.STARTING="STARTING";a.CANCELLED="CANCELLED";a.PENDING_API="PENDING_API";a.API_ERROR="API_ERROR";a.NO_OFFERS="NO_OFFERS";a.PENDING_MODULE="PENDING_MODULE";a.READY="READY"})(Zc||(Zc={}));var u={topics:{},on:function(a,b,c){T(this.topics[a])||
(this.topics[a]=[]);var d;c&&(d=function(a){Id(a,c)&&b(a)});this.topics[a].push(d||b)},publish:function(a,b){v(this.topics[a]||[],function(a){q(a)&&a(b)})}},P=function(){function a(){var a=this;l(this,"ready",void 0);l(this,"pendingCallbacks",void 0);l(this,"subReadyStateList",void 0);l(this,"isReady",function(){return a.dependsOnSubReadyState()?Kd(a.subReadyStateList,function(a){return a.isReady()}):a.ready});l(this,"setReady",function(){a.dependsOnSubReadyState()||a.ready||(a.ready=!0,a.callPendingCallbacks())});
l(this,"waitFor",function(b){b=Da(b,function(a){return!!a});a.subReadyStateList=a.subReadyStateList.concat(b);a.isReady()?a.callPendingCallbacks():b.forEach(function(b){b.whenReady(a.whenSubReadyStateIsReady)})});l(this,"whenSubReadyStateIsReady",function(){a.isReady()&&a.callPendingCallbacks()});this.ready=!1;this.pendingCallbacks=[];this.subReadyStateList=[]}var b=a.prototype;b.whenReady=function(a){this.isReady()?a():this.pendingCallbacks.push(a)};b.dependsOnSubReadyState=function(){return 0!==
this.subReadyStateList.length};b.callPendingCallbacks=function(){this.pendingCallbacks.forEach(function(a){setTimeout(a,0)});this.pendingCallbacks=[]};return a}(),ca;(function(a){a.PRE_PAGE_LOAD="PRE_PAGE_LOAD";a.POST_PAGE_LOAD="POST_PAGE_LOAD";a.AUX="AUX"})(ca||(ca={}));var R=new (function(){function a(a,b){var c=this;l(this,"requestBeaconAPI",void 0);l(this,"beaconRequestHandler",void 0);l(this,"requestsHistory",void 0);l(this,"noRequestPendingReadyState",void 0);l(this,"beaconApiResponseReadyState",
void 0);l(this,"postPageLoadCallReadyState",void 0);l(this,"beaconFullyReadyState",void 0);l(this,"whenNoRequestsPending",function(a){c.noRequestPendingReadyState.whenReady(a)});l(this,"whenBeaconApiRequestCompleted",function(a){c.beaconApiResponseReadyState.whenReady(a)});l(this,"whenPostPageLoadBeaconCallCompleted",function(a){c.postPageLoadCallReadyState.whenReady(a)});l(this,"whenBeaconFullyReady",function(a){c.beaconFullyReadyState.whenReady(a)});l(this,"sendBeaconRequest",function(a,b){var d=
0===a.length,e={readyState:new P,requestedDomains:a,response:null,beaconCallType:b};c.hasFetchedAtLeastOnce()&&d?(c.requestsHistory.push(e),e.readyState.setReady()):c.requestBeaconAPI(a,b,function(b){b=A({requestedDomains:a},b);c.beaconRequestHandler(b);e.response=b;e.readyState.setReady()});c.updateRequestsHistory(e);e.readyState.whenReady(function(){e.response&&u.publish("EVENTS__BEACON__REQUEST_COMPLETED",e);c.resolveReadyStatesOnRequestCompleted(e)});return e});this.requestBeaconAPI=a;this.beaconRequestHandler=
b;this.requestsHistory=[];this.noRequestPendingReadyState=new P;this.noRequestPendingReadyState.setReady();this.beaconApiResponseReadyState=new P;this.postPageLoadCallReadyState=new P;this.beaconFullyReadyState=Ld(this.beaconApiResponseReadyState,this.postPageLoadCallReadyState)}var b=a.prototype;b.updateRequestsHistory=function(a){this.requestsHistory.push(a);this.noRequestPendingReadyState.waitFor([a.readyState])};b.resolveReadyStatesOnRequestCompleted=function(a){a.response&&!this.beaconApiResponseReadyState.isReady()&&
this.beaconApiResponseReadyState.setReady();a.beaconCallType===ca.POST_PAGE_LOAD&&this.postPageLoadCallReadyState.setReady()};b.hasFetchedAtLeastOnce=function(){return 0!==this.requestsHistory.length};return a}())(function(a,b,c){a=JSON.stringify({pubcode:Kb,page:m.location.href,domains:a,link_swapping:!1});a={headers:{"Content-type":"application/x-www-form-urlencoded"},data:ia({data:a}),withCredentials:!0};var d=Ya();"production"!==Le&&(d._=b);Fa.post(""+Je,d,c,a)},function(a){var b={};a.country&&
(b.country=a.country.toUpperCase());a.country_state&&(b.countryState=a.country_state);a.guid&&""===k.cookie&&(b.cookie=a.guid);J(a.consent)&&(b.consent=a.consent);a.csp&&(b.cookieSyncString=a.csp);a.ts&&(b.lastBeaconTimestamp=a.ts);A(k,b);Jd(a.requestedDomains,a.merchant_domains)}),Q;(Q||(Q={})).ANCHOR_CLICK_INTERCEPTOR="ANCHOR_CLICK_INTERCEPTOR";var oc={},V;(function(a){a.LEFT_CLICK="LEFT_CLICK";a.MIDDLE_CLICK="MIDDLE_CLICK";a.OTHER_CLICK="OTHER_CLICK"})(V||(V={}));var pa;(function(a){a[a.LINK_SWAPPING=
0]="LINK_SWAPPING";a[a.CONSENT=1]="CONSENT";a[a.INCENTIVE=2]="INCENTIVE";a[a.SKIMLINKS=3]="SKIMLINKS"})(pa||(pa={}));var $c={}.hasOwnProperty;var wb=0;var xb=null;var yb=0;var Qa=!1;var Ra={};var cf=function(a){Ra[a]=Ra[a]||0;Ra[a]++;return a+"_"+Ra[a]};var df=function(a){var b;var c=b=null;if(-1!==a.indexOf(".")){a=a.split(".");var d=a[0];c=a[1]}else-1!==a.indexOf("[class=")?(a=a.split("[class="),d=a[0],c=a[1].split("]"),c=c[0]):-1!==a.indexOf("[class^=")?(a=a.split("[class^="),d=a[0],c=a[1].split("]"),
c=c[0]):-1!==a.indexOf("[id*=")?(a=a.split("[id*="),d=a[0],b=a[1].split("]"),b=b[0]):d=a;return{tag:d,id:b,"class":c}};var va=function(a,b){var c;var d=b.split(",");var e=0;for(c=d.length;e<c;e++){b=d[e];b=C(b);b=df(b);var g=!0;var n=(n="string"===typeof a.className?a.className:"")||("function"===typeof a.getAttribute?a.getAttribute("class"):void 0)||"";var h=("function"===typeof a.getAttribute?a.getAttribute("id"):void 0)||"";!b.tag||a.nodeName&&a.nodeName.toLowerCase()===b.tag||(g=!1);b["class"]&&
(!n||n!==b["class"]&&0!==n.indexOf(b["class"]))&&(g=!1);b.id&&(!h||h!==b.id&&-1===h.indexOf(b.id))&&(g=!1);if(g)return!0}return!1};var ad=function(a,b){return va(a,b)?[a]:nc(a.querySelectorAll(b))};var ef=function(a,b){return 0<a.querySelectorAll(b).length};var zb=function(a,b){return 0===b.length||va(a,b.join(","))?!0:a.parentNode?zb(a.parentNode,b):!1};var bd=function d(b,c){return 0===c.length?!1:va(b,c.join(","))?!0:b.parentNode?d(b.parentNode,c):!1};var ff=function(b){var c=b.offsetWidth;b=b.offsetHeight;
return 468===c&&60===b||234===c&&60===b||728===c&&90===b||300===c&&250===b||250===c&&250===b||336===c&&280===b||160===c&&600===b||120===c&&600===b?!0:!1};var gf=function(){var b=[];b.push("div.widget-content");b.push("div.googleAdText");b.push("div[id=ad]");b.push("div[id=banner]");b.push("div[id=advertisement]");b.push("div[id=adv_container]");b.push("div.ad");b.push("div.banner");b.push("div.advertisement");b.push("div.ad_container");b.push("span.IL_AD");b.push("div[id=fave-ext-container]");b.push("span.skimlinks-unlinked");
-1!==m.location.href.indexOf(".google.")?(b.push("td.gac_c"),b.push("table[id=mbEnd]"),b.push("div[id=mbEnd]"),b.push("span[id=taw]"),b.push("td.std"),b.push("div.std"),b.push("table.gssb_e"),b.push("div.c"),b.push("div[id=tads]")):-1!==m.location.href.indexOf(".yahoo.")?(b.push("ul.spns,ul.reducepx-spnslist"),b.push("ul[class*=reducepx-spnslist]"),b.push("ul[id=east]")):-1!==m.location.href.indexOf(".aol.")?(b.push("div.sllLink"),b.push("div.n")):-1!==m.location.href.indexOf(".bing.")&&(b.push("div.sb_adsW"),
b.push("div[id=sidebar]"),b.push("div.sb_adsWv2"),b.push("div.sb_adsNv2"),b.push("div[class*=sb_ads]"));return b};var hf=function(b){var c;var d={};var e=0;for(c=b.length;e<c;e++){var g=b[e];d[g]=!0}return d};var jf=function(){wb=0;u.publish("dom_changed")};var kf=function(b,c,d,e){var g,n,h;if((g=b.className||("function"===typeof b.getAttribute?b.getAttribute("class"):void 0)||"")&&("skimlinks-unlinked"===g||"skimwords-link"===g))return!1;if(0===d.length&&0===c.length)return z.traverse_node(b,!1,
"","",e);if(0!==d.length){if(!bd(b,d)){g=z.get_exclude_selector(d);d=z.get_exclude_selector([]);var t=g.selector;var f=g.needed;var k=d.selector;if(0===c.length||zb(b,c))return z.traverse_node(b,f,k,t,e);g=[];var m=0;for(h=c.length;m<h;m++){d=c[m];var l=ad(b,d);l.length?g.push(function(){var b;var c=[];var d=0;for(b=l.length;d<b;d++)n=l[d],c.push(z.traverse_node(n,f,k,t,e));return c}()):g.push(void 0)}return g}}else if(0!==c.length){if(zb(b,c))return z.traverse_node(b,!1,"","",e);h=[];g=0;for(m=c.length;g<
m;g++)d=c[g],l=ad(b,d),l.length?h.push(function(){var b;var c=[];var d=0;for(b=l.length;d<b;d++)n=l[d],c.push(z.traverse_node(n,!1,"","",e));return c}()):h.push(void 0);return h}};F(function(b){b=b.relatedNode||!1;if(!b||qa.send_in_progress||f("stop_skimwords_ajax"))return!1;xb&&clearTimeout(xb);wb++;1===wb&&z.reset();kf(b,qa.settings.includes||[],qa.settings.excludes||[],qa.settings.read_onlys||[]);if(z.get_non_colliding_nodes()&&1<=yb)return xb=K(function(){jf()},1E3)});var z=function(){var b={};
return{traverse:function(c,d,e,g){c=c||[];d=d||[];e=e||[];return b&&b.length&&!g?b:this.traverse_dom(c,d,e)},traverse_dom:function(c,d,e){var g,n;if(Qa)return b;Qa=!0;var h=this.get_exclude_selector(d);var t=this.get_exclude_selector([]);d=h.selector;h=h.needed;t=t.selector;0===c.length&&c.push("body");c=c.concat(e);for(var f=0,k=c.length;f<k;f++){var m=c[f];m=rc(m);m=document.querySelectorAll(m);var l=g=0;for(n=m.length;g<n;l=++g)l=m[l],this.traverse_node(l,h,t,d,e)}return b},traverse_node:function(c,
d,e,g,n){var h=[];var f=0;for(h.push({node:c,tagName:"",readOnly:!1,parent_id:null});f<h.length;)!(c=h[f].node)||ff(c)||Y(c,"noskimwords")||Y(c,"noskim")||d&&""!==e&&va(c,e)||(h[f].readOnly=!1,c.nodeName&&"#text"!==c.nodeName?(h[f].tagName=c.nodeName,null!==h[f].parent_id&&(h[f].readOnly=h[h[f].parent_id].readOnly),h[f].readOnly||(d&&va(c,g)?h[f].readOnly=!0:r(n,c.nodeName.toLowerCase())&&(h[f].readOnly=!0)),r(n,c.nodeName.toLowerCase())&&(h[f].readOnly=!0)):null!==h[f].parent_id&&(h[f].tagName=h[h[f].parent_id].tagName,
h[f].readOnly=h[h[f].parent_id].readOnly),"msie"===k.detect.browser&&9>k.detect.version&&h[f].readOnly||(c.hasChildNodes()?h=this.add_child_nodes(h[f],f,h):this._add(c,!1,h[f].tagName,h[f].readOnly))),f++;return b},is_traversed:function(){return Qa},is_good_tag:function(b){return hf("p body div span ul ol li table tbody td tr th tfoot col colgroup em strong big small blockquote cite b dl dfn dd dt ins form legend noframes pre noscript center font i article section main".split(" "))[b.nodeName.toLowerCase()]?
!0:!1},is_html:function(b){return(b=C(b))&&"<"===b[0]},get_non_colliding_nodes:function(){var c;var d=b;var e={};yb=0;for(c in d)$c.call(d,c)&&(e[c]=d[c],yb++);return e},get_as_hash_node_dict:function(){var c;var d={};for(c in b){var e=b[c];G(b,c)&&(d[c]=e)}return d},get_as_pair_array:function(){var c;var d=[];for(c in b)$c.call(b,c)&&d.push([c,b[c]]);return d},get_exclude_selector:function(b,d){var c,g,f;var h=[];if(!d){d=document.getElementsByTagName("body");if(!d.length)return{needed:!1,selector:""};
d=d[0]}b=b.concat(gf());var k=c=0;for(g=b.length;c<g;k=++c)b[k]=rc(b[k]);c=!1;g="";var m=0;for(f=b.length;m<f;m++)k=b[m],ef(d,k)&&h.push(k);h.length&&(c=!0,g=h.join(",").replace("class=","class^="));return{needed:c,selector:g}},length:function(){return Object.keys(b).length},reset:function(){b=[];return Qa=!1},add_child_nodes:function(b,d,e){var c,f;var h=b.node.childNodes;var k=0;for(f=h.length;k<f;k++)(c=h[k])&&c.nodeName&&!this._add(c,!1,b.tagName,b.readOnly)&&this.is_good_tag(c)&&e.push({node:c,
tagName:b.tagName,readOnly:b.readOnly,parent_id:d});return e},add_node:function(b,d){return this._add(b,d)},_add:function(c,d,e,g){var f=null;"#text"===c.nodeName&&(f=C(c.nodeValue));d=d||!1;if("msie"===k.detect.browser&&9>k.detect.version&&g)return!1;if("msie"!==k.detect.browser||9<=k.detect.version)try{c.meta={ElementTag:e,ReadOnly:g}}catch(h){}if(f&&!this.is_html(f)&&3<=f.length){if(d&&"-1"===d)return!1;d=this._skim_id_hash(f,d);if(!d)return!1;b[d]=c}return f?!0:!1},_skim_id_hash:function(b){if(!b)return"";
var c=C(b.replace(/\s+/g," ")).length;b=b.replace(/[:\s]*/g,"");c=c+":"+b.substring(0,20);return c=cf(c)}}}();var Xd=function(b,c,d){if(fa)return!1;var e=(b.data?b.data:b.childNodes[0].data).replace(c.repl_regex,c.replacement);var g=document.createElement("span");c=document.createDocumentFragment();g.innerHTML=e;if("msie"===k.detect.browser&&9>k.detect.version){e=b.previousSibling;var f=/^\s/;e&&e.nodeValue&&e.nodeValue.length&&f.test(e.nodeValue[e.nodeValue.length-1])&&(e.nodeValue+=" ");(e=b.nextSibling)&&
e.nodeValue&&e.nodeValue.length&&f.test(e.nodeValue[0])&&(e.nodeValue=" "+e.nodeValue)}for(;g.firstChild;)"#text"===g.firstChild.nodeName?(e=c.appendChild(g.firstChild),z.add_node(e)):(e=c.appendChild(g.firstChild),null===e||d||Fb(e,!0));if(d=b.parentNode)return d.replaceChild(c,b)};var w={campaign_ids:[],loading_started:(new Date).getTime(),linksImpressions:{skimlinks:{count:0,urls:{}},skimwords:{count:0,urls:{}},unlinked:{count:0,urls:{}}},awaitedModules:[]},Wd=new P,id=[".noskim",".noskimwords",
".noskimw"];var Yd=function(b){mb(b,"click",vc);Vc||mb(b,"contextmenu",vc);return Fb(b,!1)};var lf=function(b,c,d,e){var g=bf(b);c=lb(c);g="(?:^|[\\s]+)(?:\\\\;\\.|,\\'\\\"\\(\\)\\/:\\?])?("+g+")(?:\\'s)?(?:[\\\\;,\\.\\'\\\"|\\(\\)\\/:\\?])*(?:[\\s]+|$)";b=Rb(lb(b));c='$1$2<a href="'+c+'" class="'+e+'"  data-skimwords-word="'+b+'"  data-skim-creative="'+d+'" title="">$3$4</a>$5$6';d=g.replace(/\?:/g,"");return{search_regex:new RegExp(g,"i"),repl_regex:new RegExp(d,"i"),repl_text:c}};var fd=function(b,
c){var d,e,g;if(!b||bd(b,["span.skimlinks-unlinked"]))return[[],[]];var f=b.data;var h=[];var m=[];for(e=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^[\]\s]*\b|$/gi;d=e.exec(f);){var l=d[0];if("link.phrase"!==l){var p=d.index;if(0<C(l).length&&-1===l.indexOf("/.")&&-1===l.indexOf("...")){var r=l;0!==l.indexOf("http")&&0!==l.indexOf("//")&&(r="msie"===k.detect.browser&&6>=k.detect.version?"http://"+l:"//"+l);d=ja(r);var v=jd({OriginalPhrase:""+l,Url:r,Title:"",ActionType:2,
GroupId:0,Unlinked:!0});(g=lf(""+l,r,Ma.creative,"skimlinks-unlinked"))&&m.push({start:p,text:""+lb(l),domain:d,repl_regex:g.repl_regex,replacement:g.repl_text,regex:g.search_regex,phrase:v,link:r});h.push(d)}else break}}if(m.length){var q=c;r="skimlinks-unlinked";var x;l=document.createDocumentFragment();var u=0;d=[];p=b.nodeValue;e=[];f=b.parentNode;r||(r="skimwords-potential");q||(q="-1");if(f){v=0;for(x=m.length;v<x;v++){var w=m[v];var y=document.createElement("span");y.className=r;g=document.createTextNode(p.substring(u,
w.start));l.appendChild(g);y.innerHTML=w.text;l.appendChild(y);u={};u.node=y;u.match=w;E(u,"occurrence",w.target_occurrence);d.push(u);u=w.start+w.text.length;e.push(g);z.add_node(g,q)}m=document.createTextNode(p.substring(u));e.push(m);l.appendChild(m);z.add_node(m,q);f.replaceChild(l,b)}q=[d,e];m=q[0];q=q[1];l=0;for(e=m.length;l<e;l++)f=m[l],Ma.url_spans.push(f)}q||(q=[]);return[h,q]};var gd=function(b){var c;if(p.exclude.length){var d=p.exclude;var e=0;for(c=d.length;e<c;e++){var g=d[e];if(g===
b)return!1}}if(p.include.length){d=p.include;e=0;for(c=d.length;e<c;e++)if(g=d[e],g===b)return!0;return!1}return!0};var de="AT BE BG CY CZ DE DK EE ES FI FR GB GR HR HU IE IT LT LU LV MT NL PL PT RO SE SI SK".split(" ");B.bind(null,"InvalidVariantConfig");var Na=function(b){ae(b)?($d(b),b=Zd(b)):b=b[Math.floor(b.length*Math.random())];return b}([{id:1,moduleName:"ConsentA",getUrl:function(b,c){return function(d){d=r(c,d)?d:"en";return Ie+"/Consent_"+b+"_"+d+".js"}}("A",["bg","de","el","en","es","fr","it","pl","pt","sk"])}]),
ne={AT:"de",BE:"fr",BG:"bg",CY:"el",CZ:"cs",DE:"de",DK:"da",EE:"et",ES:"es",FI:"fi",FR:"fr",GB:"en",GR:"el",HR:"hr",HU:"hu",IE:"en",IT:"it",LT:"lt",LU:"fr",LV:"lv",MT:"en",NL:"en",PL:"pl",PT:"pt",RO:"ro",SE:"sv",SI:"sl",SK:"sk"},dd=[{label:"lotame",url:"https://sync.crwdcntrl.net/map/c=7505/tp=SKIM/?https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dlotame%26skim_mapping%3Dtrue%26provider_id%3D%24%7Bprofile_id%7D",resyncAfter:[2,"days"],priority:1,iabVendorId:95,active:!0,isCcpaSensitive:!0},{label:"blue_kai",
url:"https://stags.bluekai.com/site/27381?redir=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dblue_kai%26skim_mapping%3Dtrue%26provider_id%3D%24_BK_UUID",resyncAfter:[1,"days"],priority:2,iabVendorId:null,active:!0,isCcpaSensitive:!0},{label:"dfp",url:"https://cm.g.doubleclick.net/pixel?google_nid=skimlinks_ddp&google_cm",resyncAfter:[1,"days"],priority:2,iabVendorId:null,active:!0,isCcpaSensitive:!0},{label:"mediamath",url:"https://pixel.mathtag.com/sync/img?redir=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dmediamath%26skim_mapping%3Dtrue%26provider_id%3D%5BMM_UUID%5D%26provider_dc%3D%5BMT_DC%5D",
resyncAfter:[1,"days"],priority:2,iabVendorId:79,active:!0,isCcpaSensitive:!0},{label:"app_nexus",url:"https://secure.adnxs.com/getuid?https%3A%2F%2Fx.skimresources.com%2F%3Fprovider_id%3D%24UID%26provider%3Dapp_nexus%26skim_mapping%3Dtrue",resyncAfter:[1,"days"],priority:2,iabVendorId:32,active:!0,isCcpaSensitive:!0},{label:"eyeota",url:"https://ps.eyeota.net/match?gdpr=${SKIM__GDPR_APPLICABLE}&gdpr_consent=${SKIM__CONSENT_STRING}&bid=dn9h51u&r=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Deyeota%26provider_id%3D%7BUUID_dn9h51u%7D%26skim_mapping%3Dtrue",
resyncAfter:[1,"days"],priority:2,iabVendorId:120,active:!0,excludedCountries:"AF BH IR IQ IL JO KW LB OM PK PS QA SA SY AE YE DZ AO BJ BW BF BI CM CV CF TD KM CD CG CI DJ EG GQ ER SZ ET GA GM GH GN GW KE LS LR LY MG MW ML MR MU MA MZ NA NE NG RW SH ST SN SC SL SO ZA SS SD TZ TG TN UG ZM ZW BO CL CO CR CU DO EC SV GF GP GT HT HN MQ NI PA PY PE PR BL MF PM UY VE RU".split(" "),isCcpaSensitive:!0},{label:"exelate",url:"https://x.skimresources.com/?provider=exelate&gdpr=${SKIM__GDPR_APPLICABLE}&gdpr_consent=${SKIM__CONSENT_STRING}",
resyncAfter:[1,"days"],priority:1,iabVendorId:373,active:!0,isCcpaSensitive:!0},{label:"exelate_dbm",url:"https://cm.g.doubleclick.net/pixel?google_nid=exelate&google_cm&google_sc",resyncAfter:[2,"days"],priority:2,iabVendorId:null,active:!0,includedCountries:["GB","DE","IT","FR","ES"],isCcpaSensitive:!0},{label:"exelate_tradedesk",url:"https://match.adsrvr.org/track/cmf/generic?ttd_pid=exelate&ttd_tpi=1",resyncAfter:[2,"days"],priority:2,iabVendorId:21,active:!0,includedCountries:["GB","DE","IT"],
isCcpaSensitive:!0},{label:"exelate_adform",url:"https://dmp.adform.net/serving/cookie/match/?party=1012",resyncAfter:[2,"days"],priority:2,iabVendorId:50,active:!0,includedCountries:["DE","ES"],isCcpaSensitive:!0},{label:"exelate_mediamath",url:"https://sync.mathtag.com/sync/img?mt_exid=10008&redir=https%3A%2F%2Floadm.exelator.com%2Fload%2F%3Fp%3D204%26g%3D101%26j%3D0%26buid=[MM_UUID]",resyncAfter:[2,"days"],priority:2,iabVendorId:79,active:!0,includedCountries:["IT","ES"],isCcpaSensitive:!0},{label:"exelate_adobe",
url:"https://dpm.demdex.net/ibs:dpid=3&&redir=https%3A%2F%2Floadm.exelator.com%2Fload%2F%3Fp%3D204%26g%3D091%26j%3D0%26bi%3D%24%7BDD_UUID%7D",resyncAfter:[2,"days"],priority:2,iabVendorId:264,active:!0,includedCountries:["FR"],isCcpaSensitive:!0},{label:"exelate_appnexus",url:"https://ib.adnxs.com/getuid?https://loadm.exelator.com/load/?p=204&g=013&bi=$UID&j=0",resyncAfter:[2,"days"],priority:2,iabVendorId:32,active:!0,includedCountries:["GB","FR"],isCcpaSensitive:!0},{label:"exelate_teads",url:"https://sync.teads.tv/ex/sync",
resyncAfter:[2,"days"],priority:2,iabVendorId:132,active:!0,includedCountries:["GB","DE","IT","FR","ES"],isCcpaSensitive:!0},{label:"avocet",url:"https://ads.avocet.io/getuid?url=https%3A%2F%2Fx.skimresources.com%2F%3Fskim_mapping%3Dtrue%26provider%3Davocet%26provider_id%3D%7B%7BUUID%7D%7D",resyncAfter:[1,"days"],priority:3,iabVendorId:63,active:!0,isCcpaSensitive:!0},{label:"tapad",url:"https://x.skimresources.com/?provider=tapad",resyncAfter:[3,"days"],priority:3,iabVendorId:89,active:!0,isCcpaSensitive:!0},
{label:"trade_desk",url:"https://match.adsrvr.org/track/cmf/generic?ttd_pid=qakudad&ttd_tpi=1",resyncAfter:[3,"days"],priority:3,iabVendorId:21,active:!0,isCcpaSensitive:!0},{label:"zeotap_dbm",url:"https://x.skimresources.com/?provider=zeotap_dbm",resyncAfter:[5,"days"],priority:2,iabVendorId:null,active:!0,isCcpaSensitive:!0},{label:"zeotap_us_latam",url:"https://x.skimresources.com/?provider=zeotap_us_latam",resyncAfter:[5,"days"],priority:2,iabVendorId:null,active:!0,includedCountries:"US MX BR PE CL AR CO".split(" "),
isCcpaSensitive:!0}],Cc=new P,y={},ge={async:!0,onError:function(){},onLoad:function(){}},ra=Dc()?window.top:window,Gc={},mf="AT BE BG CY DE ES FR GB GR IE IT LU MT NL PL PT SK".split(" "),me=W(function(){var b=Dc()?window.top:window;if(q(b.__cmp)||"msie"===k.detect.browser&&8>=k.detect.version)return!1;if(Xc||Tb("skimlinks_force_consent"))return!0;var c=wa();b=D(y,["country"],k.country);c=J(c);b=!!b&&r(mf,b.toUpperCase());return!c&&b}),te=["skimlinks_included_ids","skimlinks_byrel","skimlinks_exrel",
"skimlinks_included_classes"],nf=function(){function b(){l(this,"SERVICES",b.SERVICES);l(this,"getService",na);l(this,"trackEvent",mc);u.on("skim_js_init",this.onInit.bind(this));u.on("skim_js_start",this.onStart.bind(this));R.whenBeaconFullyReady(this.whenBeaconFullyReady.bind(this))}var c=b.prototype;c.onInit=function(){};c.onStart=function(){};c.whenBeaconFullyReady=function(){};c.publishEvent=function(b,c){u.publish(b,c)};c.onEvent=function(b,c){u.on(b,c)};c.registerClickInterceptor=function(b,
c){na(Q.ANCHOR_CLICK_INTERCEPTOR).registerInterceptor(b,c)};return b}();l(nf,"SERVICES",Q);new P;var rb=!1,da=!1,sa=null,ta=null,Ge={detect:function(b){a:{try{var c=navigator.userAgent.toLowerCase();if(-1===c.indexOf("firefox")&&-1===c.indexOf("chrome")){da=!0;rb=!1;break a}}catch(d){}c=""+11*Math.random();sa=new Image;sa.onload=Mc;sa.src="//p.skimresources.com/px.gif?ch=*&rn=*".replace(/\*/,"1").replace(/\*/,c);ta=new Image;ta.onload=Mc;ta.src="//p.skimresources.com/px.gif?ch=*&rn=*".replace(/\*/,
"2").replace(/\*/,c)}Lc(b,250)}},cd=Qb([!!Uc&&"mouseup","click"]),of=["auxclick","contextmenu","touchstart"],pf=function(){function b(b,c){l(this,"type",void 0);l(this,"anchor",void 0);l(this,"affiliationType",void 0);l(this,"nativeEvent",void 0);l(this,"clientClickId",void 0);l(this,"targetedInterceptor",void 0);var d=Dd(b);this.type=this.getInternalClickType(c);this.anchor=b;this.affiliationType=d;this.nativeEvent=c;this.clientClickId=Za();this.targetedInterceptor=null}var c=b.prototype;c.setAnchorClickInterceptorTarget=
function(b){this.targetedInterceptor=b};c.setSourceApp=function(b){var c=this.anchor;H(c).sourceApp=b;Ja(c)};c.setLinkSwappingMatchId=function(b){var c=this.anchor;H(c).linkSwappingMatchId=b;Ja(c)};c.getInternalClickType=function(b){return r(cd,b.type)&&0===b.button?V.LEFT_CLICK:"auxclick"!==b.type&&"click"!==b.type||1!==b.button?V.OTHER_CLICK:V.MIDDLE_CLICK};return b}(),Ce=function(){function b(){var b=this;l(this,"interceptors",void 0);l(this,"onClick",function(c,d){var e=Gb(c);e&&(e.skimlinksOriginalHref&&
e.skimlinksRestoreSwappedLink(),e=new pf(e,c),b.dispatchAnchorClick(e,d))});l(this,"registerInterceptor",function(c,d){if(!q(c))throw Error("InterceptorHandler should be a function");if(L(d))throw Error("Missing priority for click interceptor");b.interceptors.push({handler:c,priority:d});b.interceptors.sort(function(b,c){return b.priority-c.priority})});l(this,"triggerLeftClickFromMouseEvent",function(c,d){var e=b.findInterceptorsWithPriority(d);if(L(d))b.onClick(c);else if(e.length)b.onClick(c,e)});
this.interceptors=[];this.initGlobalClickHandler()}var c=b.prototype;c.initGlobalClickHandler=function(){Oc(O,cd,this.onClick,!0);Oc(O,of,this.onClick,!0)};c.dispatchAnchorClick=function(b,c){var d=this;(c||this.interceptors).some(function(c){var e=c.handler;return d.isTargetedInterceptor(c,b)?e(b):!1})};c.findInterceptorsWithPriority=function(b){return Da(this.interceptors,function(c){return c.priority===b})};c.isTargetedInterceptor=function(b,c){var d=c.targetedInterceptor===b.priority;return!c.targetedInterceptor||
d};return b}(),ua=F(function(){sc(ca.POST_PAGE_LOAD);document.removeEventListener("DOMContentLoaded",ua);document.removeEventListener("load",ua)}),Ee={skimlinks:!1,skimwords:!1,unlinked:!1,audience:!1,GDPRConsent:!1,incentivePopup:!1};Ub&&F(function(){u.on("skim_js_init",Qd);u.on("skim_js_init",Ud);R.whenBeaconApiRequestCompleted(ce);qe();u.on("skim_js_init",ve);u.on("skim_js_start",we);De()})()})();
